name: Lint Code Base

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 5 * * *'  # Jalankan setiap hari pukul 05:00 UTC

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*\.sh$  # Hanya periksa file Bash
          VALIDATE_BASH: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_PYTHON: false  # Nonaktifkan linter Python
          VALIDATE_DOCKERFILE: false  # Nonaktifkan linter Dockerfile
          
      - name: Check for modified files
        id: check_files
        uses: tj-actions/changed-files@v34

      - name: Comment on PR
        if: steps.check_files.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: super-linter
          message: |
            Super-Linter telah menemukan beberapa masalah dalam kode Anda. Silakan periksa laporan lengkap dan perbaiki masalah yang ditemukan.

